context/wallet/index.tsx
optimize sending transaction
- step 1: sign tx to get signedTx
- step 2: send the signedTx by proxyProvider
=> [optimize] sending transaction

components/AppBar/index.tsx, components/ListPool/ListPool.module.css, components/Nav/Nav.module.css, components/Nav/SocialMenu.tsx, components/Nav/StakeMenu.tsx, components/Nav/index.tsx, components/PoolCardItem/index.tsx, components/StakedPoolCardItem/index.tsx, components/Swap/index.tsx, views/components/VotePowerChart.tsx, views/stake/farms/FarmCard.tsx, views/stake/farms/FarmStats.tsx
- remove voting power label on locked veASH chart
- responsive nav on mobile
- responsive pool/farm card layout on mobile
=> Fix: minor ui bug

components/Layout/Info.tsx, hooks/useValueChart.tsx, interface/chart.ts, interface/tokenStats.ts, next.config.js, pages/info/index.tsx, pages/info/tokens/index.tsx, views/components/VotePowerChart.tsx, views/info/OverviewLiquidityChart.tsx, views/info/OverviewVolumeChart.tsx, views/info/components/PoolsTable.tsx, views/info/components/TokenTable.tsx
- analytic overview page
- analytic overview total value locked across all pools, gov-stake
- analytic overview volume
- top pool/token by volume
=> feat: analytic overview

components/BaseTooltip/index.tsx, components/Swap/Swap.module.css, components/Swap/index.tsx, components/SwapAmount/index.tsx, components/TokenSelect/index.tsx, components/Tooltip/OnboardTooltip.tsx, hooks/useOnboarding.tsx
=> Feat: swap tooltip

components/AddLiquidityModal/index.tsx, components/RemoveLiquidityModal/index.tsx, components/Swap/index.tsx, const/dappConfig.ts, context/farms/index.tsx, context/gov/index.tsx, helper/transactionMethods.tsx, views/stake/gov/GovStats.tsx
=> Feat: gas limit

components/AddLiquidityModal/index.tsx, components/HistoryModal/index.tsx, components/Setting/index.tsx, components/Swap/index.tsx, context/swap/index.tsx, helper/cancellablePromise.ts, views/stake/farms/FarmCard.tsx
=> feat: remove add-LP constraint 1:1 tokens ratio

components/PoolCardItem/index.tsx, components/StakedPoolCardItem/index.tsx
=> feat(pool): static tooltip

components/SignTxsModal/index.tsx, components/TxsToastList/TxToast.tsx, components/TxsToastList/index.tsx, pages/_app.tsx
=> feat: collapse tx toast

components/PoolCardItem/index.tsx, components/StakeLPModal/index.tsx, components/StakedPoolCardItem/index.tsx, components/Swap/index.tsx, components/TextAmt/index.tsx, components/UnstakeLPModal/index.tsx, views/info/components/PoolsTable.tsx, views/stake/farms/FarmCard.tsx, views/stake/gov/GovStats.tsx
=> feat: update styling decimal part of numerical string

components/AddLiquidityModal/index.tsx, components/BaseTooltip/index.tsx, components/ListPool/index.tsx, components/PoolCardItem/index.tsx, components/RemoveLiquidityModal/index.tsx, components/StakedPoolCardItem/index.tsx, components/TextAmt/index.tsx, components/Tooltip/CardTooltip.tsx, components/Tooltip/OnboardTooltip.tsx, hooks/useOnboarding.tsx
=> feat: onboarding tooltip for pool page

components/GOVStakeModal/FirstStakeModal.tsx, components/GOVStakeModal/LockPeriod.tsx, components/GOVStakeModal/StakeMoreModal.tsx, const/ashswapConfig.ts, const/dappConfig.ts, const/farms.ts, const/maiarPools.ts, const/pool.ts, helper/voteEscrow.ts, pages/info/stake/index.tsx, pages/stake/gov/index.tsx, views/components/VotePowerChart.tsx, views/components/WeeklyFeeTable.tsx, views/info/Tokens/[id]/TokenChart.tsx, views/stake/gov/GovStats.tsx, views/stake/gov/components/GovMenu.tsx
- BoY cleanup
- update devnet contract
=> Feat: boy cleanup

atoms/storage.ts, components/BaseModal/index.tsx, components/BaseTooltip/index.tsx, components/BoostBar/index.tsx, components/Delayed/index.tsx, helper/voteEscrow.ts, hooks/useFarmBoostState.tsx, hooks/useFarmContract/useCalcBoost.tsx, hooks/useInputNumberString.tsx, hooks/useOnboarding.tsx, views/stake/farms/FarmBoostInfoModal.tsx, views/stake/farms/FarmBoostTooltip.tsx, views/stake/gov/boost/BoostCalcModal.tsx, views/stake/gov/boost/GovBoostStatus.tsx
- new boost calculator design
- loading spinner on boosting
- onboarding-tooltip for farm boost
=> Feat: yield boost enhance

atoms/farmsState.ts, components/BoostBar/AdvanceBoostBar.tsx, components/BoostBar/index.tsx, components/Tooltip/OnboardTooltip.tsx, helper/contracts/pool.ts, helper/farmBooster.ts, hooks/useFarmBoostState.tsx, hooks/useFarmContract/useCalcBoost.tsx, hooks/useOnboarding.tsx, hooks/useRouteModal.tsx, views/stake/farms/FarmBoostInfoModal.tsx, views/stake/farms/FarmCard.tsx, views/stake/farms/FarmsState.tsx, views/stake/gov/boost/BoostCalcModal.tsx, views/stake/gov/boost/GovBoostStatus.tsx
- yield boost tooltip, tourguide tooltip
- update boosting calculator fomular
- update pool contract endpoint
=> Feat: yield boost tooltip

components/BaseTooltip/index.tsx, components/BoostBar/AdvanceBoostBar.tsx, components/BoostBar/index.tsx, components/Tooltip/CardTooltip.tsx, views/stake/farms/FarmBoostInfoModal.tsx, views/stake/farms/FarmCard.tsx, views/stake/gov/boost/BoostCalcModal.tsx, views/stake/gov/boost/GovBoostStatus.tsx
enhance from the internal team's feedback.
=> feat: yield boost enhance from feedback

components/BoostBar/AdvanceBoostBar.tsx, helper/farmBooster.ts, views/stake/gov/boost/BoostCalcModal.tsx
* fix: yield boost calc unmatch unit
* fix: format amt boost
=> Release: v0.3.25-devnet 

assets/abi/farm.abi.json, assets/abi/fee_distributor.abi.json, assets/abi/pool.abi.json, assets/abi/voting_escrow.abi.json, atoms/transactions.ts, components/DappCoreCustom/TxCompletedTracker.tsx, components/DappCoreCustom/index.tsx, components/SignTxsModal/index.tsx, components/TxsToastList/index.tsx, const/ashswapConfig.ts, const/env.ts, const/farms.ts, const/pool.ts, context/socket/index.tsx, helper/contracts/pool.ts, package.json, pages/_app.tsx, yarn.lock
Enable socket to listen transaction events
=> Feat: socket

components/AppBar/index.tsx, components/Avatar/index.tsx, components/ConnectWalletModal/index.tsx, components/Image/index.tsx, components/Layout/Info.tsx, components/Nav/SocialMenu.tsx, components/Nav/StakeMenu.tsx, components/Token/index.tsx, next.config.js, package.json, pages/_document.tsx, pages/info/pools/[address].tsx, pages/info/stake/farms/[address].tsx, pages/info/tokens/[id].tsx, views/pool/components/ListPool/index.tsx, views/stake/LPStakeCard.tsx, views/stake/MintStakeCard.tsx, views/stake/VoteStakeCard.tsx, views/stake/farms/FarmBoostInfoModal.tsx, views/stake/gov/boost/BoostCalcModal.tsx, views/stake/gov/boost/GovBoostStatus.tsx, views/stake/mint/MintStats.tsx, views/swap/Swap.tsx
config export page for ipfs serving
=> Feat: static page

atoms/transactions.ts, components/DappCoreCustom/TxCompletedTracker.tsx, components/DappCoreCustom/index.tsx, components/HistoryModal/index.tsx, hooks/useFarmContract/useFarmClaimAll.tsx, hooks/useRecoilAdapter/useRecoilAdapter.tsx, hooks/useRefreshAfterTxCompleted.tsx, views/stake/farms/FarmBoostInfoModal.tsx
- Optimize txs status tracker (reduce API call).
- Optimize fetching balance only on tx completed.
- Update tx history list.
=> Feat: optimize tracker

views/quest/QuestOverview.tsx
Co-authored-by: Otis <otis@Otiss-MacBook-Air.local>
=> feat:ashpoint: update invitation link (#213)

components/BoostBar/AdvanceBoostBar.tsx, components/BoostBar/index.tsx, components/GOVStakeModal/FirstStakeModal.tsx, components/GOVStakeModal/LockPeriod.tsx, components/GOVStakeModal/StakeMoreModal.tsx, views/stake/gov/GovStats.tsx
- update gov typo
- adjust gov lock duration options
- fix overflow new boost text on boostbar
=> Feat: fix minor bug and adjustment
